// Material Design Icons wrapper for consistent usage
import {
  Dashboard as DashboardIcon,
  Security as SecurityIcon,
  Search as SearchIcon,
  Assessment as AssessmentIcon,
  Policy as PolicyIcon,
  Settings as SettingsIcon,
  AccountTree as NetworkIcon,
  Psychology as BrainIcon,
  Shield as ShieldIcon,
  Warning as WarningIcon,
  CheckCircle as CheckCircleIcon,
  Error as ErrorIcon,
  Info as InfoIcon,
  Visibility as EyeIcon,
  BarChart as BarChartIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  Activity as ActivityIcon,
  Schedule as ClockIcon,
  Refresh as RefreshIcon,
  Download as DownloadIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  RotateLeft as RotateLeftIcon,
  Fullscreen as FullscreenIcon,
  Share as ShareIcon,
  Notifications as NotificationsIcon,
  AccountCircle as AccountCircleIcon,
  Menu as MenuIcon,
  Close as CloseIcon,
  ExpandMore as ChevronDownIcon,
  KeyboardArrowRight as ArrowRightIcon,
  KeyboardArrowLeft as ArrowLeftIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  FileDownload as FileDownloadIcon,
  Upload as UploadIcon,
  Link as LinkIcon,
  ContentCopy as CopyIcon,
  FilterList as FilterIcon,
  Sort as SortIcon,
  MoreVert as MoreVertIcon,
  Wallet as WalletIcon,
  AccountBalance as ExchangeIcon,
  SwapHoriz as SwapIcon,
  Timeline as TimelineIcon,
  Gavel as ComplianceIcon,
  ReportProblem as ReportIcon,
  Analytics as AnalyticsIcon,
  MonetizationOn as MoneyIcon,
  AttachMoney as DollarIcon,
  TrendingFlat as TrendingFlatIcon,
  DeviceHub as HubIcon,
  Language as GlobalIcon,
  Storage as DatabaseIcon,
  Code as CodeIcon,
  Bug as BugIcon,
  Speed as SpeedIcon,
  Extension as ExtensionIcon,
  CloudSync as SyncIcon,
  Lock as LockIcon,
  LockOpen as UnlockIcon,
  VpnKey as KeyIcon,
  Fingerprint as FingerprintIcon,
  PersonSearch as PersonSearchIcon,
  Group as GroupIcon,
  Person as PersonIcon,
  Business as BusinessIcon,
  LocationOn as LocationIcon,
  DateRange as DateIcon,
  AccessTime as TimeIcon,
  History as HistoryIcon,
  Update as UpdateIcon,
  NewReleases as NewIcon,
  Star as StarIcon,
  Bookmark as BookmarkIcon,
  Flag as FlagIcon,
  Label as TagIcon,
  Category as CategoryIcon,
  LocalOffer as OfferIcon,
  Receipt as ReceiptIcon,
  Payment as PaymentIcon,
  CreditCard as CardIcon,
  RequestQuote as QuoteIcon,
  MoneyOff as MoneyOffIcon,
  PriceCheck as PriceCheckIcon,
  Paid as PaidIcon,
  CurrencyExchange as ExchangeRateIcon,
  TrendingDownIcon,
  Verified as VerifiedIcon,
  GppBad as RiskIcon,
  GppGood as SafeIcon,
  GppMaybe as MaybeIcon,
  HighlightOff as HighRiskIcon,
  CheckCircleOutline as LowRiskIcon,
  RadioButtonUnchecked as MediumRiskIcon,
  Bolt as ElectricIcon,
  FlashOn as FlashIcon,
  Whatshot as HotIcon,
  AcUnit as ColdIcon,
  Opacity as LiquidIcon,
  Grain as GrainIcon,
  Scatter as ScatterIcon,
  BubbleChart as BubbleIcon,
  DonutLarge as DonutIcon,
  PieChart as PieIcon,
  ShowChart as LineChartIcon,
  Equalizer as EqualizerIcon,
  Leaderboard as LeaderboardIcon,
  MultilineChart as MultilineChartIcon,
  CandlestickChart as CandlestickIcon,
  DataUsage as DataUsageIcon,
  QueryStats as QueryStatsIcon,
  Insights as InsightsIcon,
  TroubleshootIcon,
  Science as ScienceIcon,
  Biotech as BiotechIcon,
  Memory as MemoryIcon,
  Computer as ComputerIcon,
  PhoneAndroid as MobileIcon,
  Tablet as TabletIcon,
  Laptop as LaptopIcon,
  DesktopWindows as DesktopIcon,
  Watch as WatchIcon,
  Tv as TvIcon,
  Headset as HeadsetIcon,
  Keyboard as KeyboardIcon,
  Mouse as MouseIcon,
  Print as PrintIcon,
  Scanner as ScannerIcon,
  Wifi as WifiIcon,
  Bluetooth as BluetoothIcon,
  Nfc as NfcIcon,
  Usb as UsbIcon,
  SdCard as SdCardIcon,
  SimCard as SimCardIcon,
  Router as RouterIcon,
  Dns as DnsIcon,
  Http as HttpIcon,
  Https as HttpsIcon,
  Api as ApiIcon,
  Webhook as WebhookIcon,
  OpenInNew as OpenInNewIcon,
  Launch as LaunchIcon,
  ExitToApp as ExitIcon,
  Login as LoginIcon,
  Logout as LogoutIcon,
  PersonAdd as PersonAddIcon,
  PersonRemove as PersonRemoveIcon,
  SupervisorAccount as SupervisorIcon,
  AdminPanelSettings as AdminIcon,
  ManageAccounts as ManageAccountsIcon,
  VerifiedUser as VerifiedUserIcon,
  Block as BlockIcon,
  Check as CheckIcon,
  Clear as ClearIcon,
  Done as DoneIcon,
  Cancel as CancelIcon,
  Save as SaveIcon,
  Backup as BackupIcon,
  Restore as RestoreIcon,
  Sync as SyncIcon2,
  SyncProblem as SyncProblemIcon,
  SyncDisabled as SyncDisabledIcon,
  Cloud as CloudIcon,
  CloudDownload as CloudDownloadIcon,
  CloudUpload as CloudUploadIcon,
  CloudOff as CloudOffIcon,
  CloudQueue as CloudQueueIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  CreateNewFolder as CreateFolderIcon,
  DriveFileMove as MoveFileIcon,
  FileCopy as FileCopyIcon,
  InsertDriveFile as FileIcon,
  Description as DocumentIcon,
  PictureAsPdf as PdfIcon,
  Image as ImageIcon,
  VideoFile as VideoIcon,
  AudioFile as AudioIcon,
  Archive as ArchiveIcon,
  DataObject as JsonIcon,
  Html as HtmlIcon,
  Css as CssIcon,
  JavaScript as JsIcon,
} from '@mui/icons-material';

// Create a mapping object for easy icon replacement
export const icons = {
  // Dashboard & Navigation
  dashboard: DashboardIcon,
  security: SecurityIcon,
  search: SearchIcon,
  assessment: AssessmentIcon,
  policy: PolicyIcon,
  settings: SettingsIcon,
  
  // Core AML/Compliance
  network: NetworkIcon,
  brain: BrainIcon,
  shield: ShieldIcon,
  warning: WarningIcon,
  
  // Status indicators
  checkCircle: CheckCircleIcon,
  error: ErrorIcon,
  info: InfoIcon,
  
  // Actions
  eye: EyeIcon,
  refresh: RefreshIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  
  // Charts & Analytics
  barChart: BarChartIcon,
  trendingUp: TrendingUpIcon,
  trendingDown: TrendingDownIcon,
  trendingFlat: TrendingFlatIcon,
  pieChart: PieIcon,
  lineChart: LineChartIcon,
  
  // Time & Scheduling
  clock: ClockIcon,
  time: TimeIcon,
  history: HistoryIcon,
  schedule: ClockIcon,
  
  // UI Controls
  menu: MenuIcon,
  close: CloseIcon,
  chevronDown: ChevronDownIcon,
  arrowRight: ArrowRightIcon,
  arrowLeft: ArrowLeftIcon,
  
  // Zoom & View controls
  zoomIn: ZoomInIcon,
  zoomOut: ZoomOutIcon,
  rotateLeft: RotateLeftIcon,
  fullscreen: FullscreenIcon,
  
  // Financial & Crypto
  wallet: WalletIcon,
  exchange: ExchangeIcon,
  money: MoneyIcon,
  dollar: DollarIcon,
  payment: PaymentIcon,
  
  // Risk Levels
  risk: RiskIcon,
  safe: SafeIcon,
  maybe: MaybeIcon,
  highRisk: HighRiskIcon,
  lowRisk: LowRiskIcon,
  mediumRisk: MediumRiskIcon,
  
  // User & People
  person: PersonIcon,
  group: GroupIcon,
  personSearch: PersonSearchIcon,
  
  // System & Tech
  database: DatabaseIcon,
  code: CodeIcon,
  api: ApiIcon,
  computer: ComputerIcon,
  
  // Files & Documents
  file: FileIcon,
  document: DocumentIcon,
  folder: FolderIcon,
  
  // General
  notifications: NotificationsIcon,
  account: AccountCircleIcon,
  verified: VerifiedIcon,
  lock: LockIcon,
  unlock: UnlockIcon,
  
  // Special
  activity: ActivityIcon,
  analytics: AnalyticsIcon,
  insights: InsightsIcon,
  compliance: ComplianceIcon,
  report: ReportIcon,
};

// Export individual icons for direct use
export {
  DashboardIcon,
  SecurityIcon,
  SearchIcon,
  AssessmentIcon,
  PolicyIcon,
  SettingsIcon,
  NetworkIcon,
  BrainIcon,
  ShieldIcon,
  WarningIcon,
  CheckCircleIcon,
  ErrorIcon,
  InfoIcon,
  EyeIcon,
  BarChartIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  ActivityIcon,
  ClockIcon,
  RefreshIcon,
  DownloadIcon,
  ZoomInIcon,
  ZoomOutIcon,
  RotateLeftIcon,
  FullscreenIcon,
  ShareIcon,
  NotificationsIcon,
  AccountCircleIcon,
  MenuIcon,
  CloseIcon,
  ChevronDownIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  WalletIcon,
  ExchangeIcon,
  MoneyIcon,
  DollarIcon,
  PaymentIcon,
  RiskIcon,
  SafeIcon,
  MaybeIcon,
  HighRiskIcon,
  LowRiskIcon,
  MediumRiskIcon,
  PersonIcon,
  GroupIcon,
  PersonSearchIcon,
  DatabaseIcon,
  CodeIcon,
  ApiIcon,
  ComputerIcon,
  FileIcon,
  DocumentIcon,
  FolderIcon,
  VerifiedIcon,
  LockIcon,
  UnlockIcon,
  AnalyticsIcon,
  InsightsIcon,
  ComplianceIcon,
  ReportIcon,
};

// Default export for convenience
export default icons;
