// Material Design Icons wrapper component
// Using Material UI icons since they are already installed

import {
  Dashboard as DashboardIcon,
  Search as SearchIcon,
  Security as SecurityIcon,
  Assessment as AssessmentIcon,
  AccountBalance as AccountBalanceIcon,
  Settings as SettingsIcon,
  Notifications as NotificationsIcon,
  Person as PersonIcon,
  ExitToApp as ExitToAppIcon,
  Help as HelpIcon,
  TrendingUp as TrendingUpIcon,
  TrendingDown as TrendingDownIcon,
  CheckCircle as CheckCircleIcon,
  Cancel as CancelIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  Visibility as VisibilityIcon,
  BarChart as BarChartIcon,
  PieChart as PieChartIcon,
  Timeline as TimelineIcon,
  AccountBalanceWallet as WalletIcon,
  SwapHoriz as SwapHorizIcon,
  AttachMoney as AttachMoneyIcon,
  Gavel as GavelIcon,
  Shield as ShieldIcon,
  Report as ReportIcon,
  Analytics as AnalyticsIcon,
  FileCopy as FileCopyIcon,
  Launch as LaunchIcon,
  Refresh as RefreshIcon,
  Menu as MenuIcon,
  Close as CloseIcon,
  Add as AddIcon,
  Remove as RemoveIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  Share as ShareIcon,
  Print as PrintIcon,
  Email as EmailIcon,
  Phone as PhoneIcon,
  LocationOn as LocationOnIcon,
  DateRange as DateRangeIcon,
  AccessTime as AccessTimeIcon,
  Language as LanguageIcon,
  Public as PublicIcon,
  Lock as LockIcon,
  LockOpen as LockOpenIcon,
  Verified as VerifiedIcon,
  Block as BlockIcon,
  Flag as FlagIcon,
} from "@mui/icons-material";

// Export all icons with consistent naming
export {
  DashboardIcon,
  SearchIcon,
  SecurityIcon,
  AssessmentIcon,
  AccountBalanceIcon,
  SettingsIcon,
  NotificationsIcon,
  PersonIcon,
  ExitToAppIcon,
  HelpIcon,
  TrendingUpIcon,
  TrendingDownIcon,
  CheckCircleIcon,
  CancelIcon,
  WarningIcon,
  InfoIcon,
  VisibilityIcon,
  BarChartIcon,
  PieChartIcon,
  TimelineIcon,
  WalletIcon,
  SwapHorizIcon,
  AttachMoneyIcon,
  GavelIcon,
  ShieldIcon,
  ReportIcon,
  AnalyticsIcon,
  FileCopyIcon,
  LaunchIcon,
  RefreshIcon,
  MenuIcon,
  CloseIcon,
  AddIcon,
  RemoveIcon,
  EditIcon,
  DeleteIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  PrintIcon,
  EmailIcon,
  PhoneIcon,
  LocationOnIcon,
  DateRangeIcon,
  AccessTimeIcon,
  LanguageIcon,
  PublicIcon,
  LockIcon,
  LockOpenIcon,
  VerifiedIcon,
  BlockIcon,
  FlagIcon,
};

// Default export for convenience
export default {
  Dashboard: DashboardIcon,
  Search: SearchIcon,
  Security: SecurityIcon,
  Assessment: AssessmentIcon,
  AccountBalance: AccountBalanceIcon,
  Settings: SettingsIcon,
  Notifications: NotificationsIcon,
  Person: PersonIcon,
  ExitToApp: ExitToAppIcon,
  Help: HelpIcon,
  TrendingUp: TrendingUpIcon,
  TrendingDown: TrendingDownIcon,
  CheckCircle: CheckCircleIcon,
  Cancel: CancelIcon,
  Warning: WarningIcon,
  Info: InfoIcon,
  Visibility: VisibilityIcon,
  BarChart: BarChartIcon,
  PieChart: PieChartIcon,
  Timeline: TimelineIcon,
  Wallet: WalletIcon,
  SwapHoriz: SwapHorizIcon,
  AttachMoney: AttachMoneyIcon,
  Gavel: GavelIcon,
  Shield: ShieldIcon,
  Report: ReportIcon,
  Analytics: AnalyticsIcon,
  FileCopy: FileCopyIcon,
  Launch: LaunchIcon,
  Refresh: RefreshIcon,
  Menu: MenuIcon,
  Close: CloseIcon,
  Add: AddIcon,
  Remove: RemoveIcon,
  Edit: EditIcon,
  Delete: DeleteIcon,
  Download: DownloadIcon,
  Upload: UploadIcon,
  Share: ShareIcon,
  Print: PrintIcon,
  Email: EmailIcon,
  Phone: PhoneIcon,
  LocationOn: LocationOnIcon,
  DateRange: DateRangeIcon,
  AccessTime: AccessTimeIcon,
  Language: LanguageIcon,
  Public: PublicIcon,
  Lock: LockIcon,
  LockOpen: LockOpenIcon,
  Verified: VerifiedIcon,
  Block: BlockIcon,
  Flag: FlagIcon,
};
